### ISSUE TITLE
Changes in tailwind.js are not picking up.

### ISSUE THREAD

**Issue by manojp1988** [SantiMA10/tailwindcss-parcel-starter#1]
Any changes in tailwind.js is not picking up during hot reloading. Do you know how to do it?

**Comment by SantiMA10** [comment]
No idea, I have to investigate a bit this issue.

**Comment by jsnrynlds** [comment]
Hi @SantiMA10 — this is awesome, thanks. 
But I'm also having the same issue — actually, even when I restart localhost the changes I've made in `tailwind.js` aren't being implemented. Not sure if I'm missing something?

**Comment by SantiMA10** [comment]
Hi @jsnrynlds!
Can you try by removing the parcel `.cache` folder?

**Comment by jsnrynlds** [comment]
Thanks @SantiMA10 — that worked!
